// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/eragon-mdi/pr-reviewer-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PullRequestService is an autogenerated mock type for the PullRequestService type
type PullRequestService struct {
	mock.Mock
}

type PullRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *PullRequestService) EXPECT() *PullRequestService_Expecter {
	return &PullRequestService_Expecter{mock: &_m.Mock}
}

// Merge provides a mock function with given fields: id
func (_m *PullRequestService) Merge(id domain.PrId) (domain.PullRequest, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.PrId) (domain.PullRequest, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(domain.PrId) domain.PullRequest); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(domain.PrId) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestService_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type PullRequestService_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - id domain.PrId
func (_e *PullRequestService_Expecter) Merge(id interface{}) *PullRequestService_Merge_Call {
	return &PullRequestService_Merge_Call{Call: _e.mock.On("Merge", id)}
}

func (_c *PullRequestService_Merge_Call) Run(run func(id domain.PrId)) *PullRequestService_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.PrId))
	})
	return _c
}

func (_c *PullRequestService_Merge_Call) Return(_a0 domain.PullRequest, _a1 error) *PullRequestService_Merge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestService_Merge_Call) RunAndReturn(run func(domain.PrId) (domain.PullRequest, error)) *PullRequestService_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// NewPullRequest provides a mock function with given fields: basePR
func (_m *PullRequestService) NewPullRequest(basePR domain.PullRequestShort) (domain.PullRequest, error) {
	ret := _m.Called(basePR)

	if len(ret) == 0 {
		panic("no return value specified for NewPullRequest")
	}

	var r0 domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.PullRequestShort) (domain.PullRequest, error)); ok {
		return rf(basePR)
	}
	if rf, ok := ret.Get(0).(func(domain.PullRequestShort) domain.PullRequest); ok {
		r0 = rf(basePR)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(domain.PullRequestShort) error); ok {
		r1 = rf(basePR)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestService_NewPullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPullRequest'
type PullRequestService_NewPullRequest_Call struct {
	*mock.Call
}

// NewPullRequest is a helper method to define mock.On call
//   - basePR domain.PullRequestShort
func (_e *PullRequestService_Expecter) NewPullRequest(basePR interface{}) *PullRequestService_NewPullRequest_Call {
	return &PullRequestService_NewPullRequest_Call{Call: _e.mock.On("NewPullRequest", basePR)}
}

func (_c *PullRequestService_NewPullRequest_Call) Run(run func(basePR domain.PullRequestShort)) *PullRequestService_NewPullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.PullRequestShort))
	})
	return _c
}

func (_c *PullRequestService_NewPullRequest_Call) Return(_a0 domain.PullRequest, _a1 error) *PullRequestService_NewPullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestService_NewPullRequest_Call) RunAndReturn(run func(domain.PullRequestShort) (domain.PullRequest, error)) *PullRequestService_NewPullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Reasign provides a mock function with given fields: ctx, prReasMem
func (_m *PullRequestService) Reasign(ctx context.Context, prReasMem domain.PrReasignMember) (domain.PrWithReasignMember, error) {
	ret := _m.Called(ctx, prReasMem)

	if len(ret) == 0 {
		panic("no return value specified for Reasign")
	}

	var r0 domain.PrWithReasignMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PrReasignMember) (domain.PrWithReasignMember, error)); ok {
		return rf(ctx, prReasMem)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PrReasignMember) domain.PrWithReasignMember); ok {
		r0 = rf(ctx, prReasMem)
	} else {
		r0 = ret.Get(0).(domain.PrWithReasignMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PrReasignMember) error); ok {
		r1 = rf(ctx, prReasMem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestService_Reasign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reasign'
type PullRequestService_Reasign_Call struct {
	*mock.Call
}

// Reasign is a helper method to define mock.On call
//   - ctx context.Context
//   - prReasMem domain.PrReasignMember
func (_e *PullRequestService_Expecter) Reasign(ctx interface{}, prReasMem interface{}) *PullRequestService_Reasign_Call {
	return &PullRequestService_Reasign_Call{Call: _e.mock.On("Reasign", ctx, prReasMem)}
}

func (_c *PullRequestService_Reasign_Call) Run(run func(ctx context.Context, prReasMem domain.PrReasignMember)) *PullRequestService_Reasign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PrReasignMember))
	})
	return _c
}

func (_c *PullRequestService_Reasign_Call) Return(_a0 domain.PrWithReasignMember, _a1 error) *PullRequestService_Reasign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestService_Reasign_Call) RunAndReturn(run func(context.Context, domain.PrReasignMember) (domain.PrWithReasignMember, error)) *PullRequestService_Reasign_Call {
	_c.Call.Return(run)
	return _c
}

// NewPullRequestService creates a new instance of PullRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestService {
	mock := &PullRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
