// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/eragon-mdi/pr-reviewer-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MemberService is an autogenerated mock type for the MemberService type
type MemberService struct {
	mock.Mock
}

type MemberService_Expecter struct {
	mock *mock.Mock
}

func (_m *MemberService) EXPECT() *MemberService_Expecter {
	return &MemberService_Expecter{mock: &_m.Mock}
}

// ReasignMember provides a mock function with given fields: _a0, _a1, _a2
func (_m *MemberService) ReasignMember(_a0 context.Context, _a1 domain.MemberId, _a2 domain.MembersHistories) (domain.MemberId, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ReasignMember")
	}

	var r0 domain.MemberId
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MemberId, domain.MembersHistories) (domain.MemberId, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MemberId, domain.MembersHistories) domain.MemberId); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(domain.MemberId)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MemberId, domain.MembersHistories) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MemberService_ReasignMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReasignMember'
type MemberService_ReasignMember_Call struct {
	*mock.Call
}

// ReasignMember is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.MemberId
//   - _a2 domain.MembersHistories
func (_e *MemberService_Expecter) ReasignMember(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MemberService_ReasignMember_Call {
	return &MemberService_ReasignMember_Call{Call: _e.mock.On("ReasignMember", _a0, _a1, _a2)}
}

func (_c *MemberService_ReasignMember_Call) Run(run func(_a0 context.Context, _a1 domain.MemberId, _a2 domain.MembersHistories)) *MemberService_ReasignMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MemberId), args[2].(domain.MembersHistories))
	})
	return _c
}

func (_c *MemberService_ReasignMember_Call) Return(_a0 domain.MemberId, _a1 error) *MemberService_ReasignMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MemberService_ReasignMember_Call) RunAndReturn(run func(context.Context, domain.MemberId, domain.MembersHistories) (domain.MemberId, error)) *MemberService_ReasignMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMemberService creates a new instance of MemberService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberService {
	mock := &MemberService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
