// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/eragon-mdi/pr-reviewer-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	servpullrequests "github.com/eragon-mdi/pr-reviewer-service/internal/service/pull-requests"
)

// PullRequestsRepository is an autogenerated mock type for the PullRequestsRepository type
type PullRequestsRepository struct {
	mock.Mock
}

type PullRequestsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PullRequestsRepository) EXPECT() *PullRequestsRepository_Expecter {
	return &PullRequestsRepository_Expecter{mock: &_m.Mock}
}

// BeginReasignTx provides a mock function with given fields: _a0
func (_m *PullRequestsRepository) BeginReasignTx(_a0 context.Context) (servpullrequests.ReassignTx, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for BeginReasignTx")
	}

	var r0 servpullrequests.ReassignTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (servpullrequests.ReassignTx, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) servpullrequests.ReassignTx); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servpullrequests.ReassignTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestsRepository_BeginReasignTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginReasignTx'
type PullRequestsRepository_BeginReasignTx_Call struct {
	*mock.Call
}

// BeginReasignTx is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *PullRequestsRepository_Expecter) BeginReasignTx(_a0 interface{}) *PullRequestsRepository_BeginReasignTx_Call {
	return &PullRequestsRepository_BeginReasignTx_Call{Call: _e.mock.On("BeginReasignTx", _a0)}
}

func (_c *PullRequestsRepository_BeginReasignTx_Call) Run(run func(_a0 context.Context)) *PullRequestsRepository_BeginReasignTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PullRequestsRepository_BeginReasignTx_Call) Return(_a0 servpullrequests.ReassignTx, _a1 error) *PullRequestsRepository_BeginReasignTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestsRepository_BeginReasignTx_Call) RunAndReturn(run func(context.Context) (servpullrequests.ReassignTx, error)) *PullRequestsRepository_BeginReasignTx_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullRequest provides a mock function with given fields: _a0
func (_m *PullRequestsRepository) CreatePullRequest(_a0 domain.PullRequest) (domain.PullRequest, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.PullRequest) (domain.PullRequest, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain.PullRequest) domain.PullRequest); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(domain.PullRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestsRepository_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type PullRequestsRepository_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - _a0 domain.PullRequest
func (_e *PullRequestsRepository_Expecter) CreatePullRequest(_a0 interface{}) *PullRequestsRepository_CreatePullRequest_Call {
	return &PullRequestsRepository_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", _a0)}
}

func (_c *PullRequestsRepository_CreatePullRequest_Call) Run(run func(_a0 domain.PullRequest)) *PullRequestsRepository_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.PullRequest))
	})
	return _c
}

func (_c *PullRequestsRepository_CreatePullRequest_Call) Return(_a0 domain.PullRequest, _a1 error) *PullRequestsRepository_CreatePullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestsRepository_CreatePullRequest_Call) RunAndReturn(run func(domain.PullRequest) (domain.PullRequest, error)) *PullRequestsRepository_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MergePullRequest provides a mock function with given fields: _a0
func (_m *PullRequestsRepository) MergePullRequest(_a0 domain.PrId) (domain.PullRequest, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequest")
	}

	var r0 domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.PrId) (domain.PullRequest, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain.PrId) domain.PullRequest); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(domain.PrId) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestsRepository_MergePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePullRequest'
type PullRequestsRepository_MergePullRequest_Call struct {
	*mock.Call
}

// MergePullRequest is a helper method to define mock.On call
//   - _a0 domain.PrId
func (_e *PullRequestsRepository_Expecter) MergePullRequest(_a0 interface{}) *PullRequestsRepository_MergePullRequest_Call {
	return &PullRequestsRepository_MergePullRequest_Call{Call: _e.mock.On("MergePullRequest", _a0)}
}

func (_c *PullRequestsRepository_MergePullRequest_Call) Run(run func(_a0 domain.PrId)) *PullRequestsRepository_MergePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.PrId))
	})
	return _c
}

func (_c *PullRequestsRepository_MergePullRequest_Call) Return(_a0 domain.PullRequest, _a1 error) *PullRequestsRepository_MergePullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestsRepository_MergePullRequest_Call) RunAndReturn(run func(domain.PrId) (domain.PullRequest, error)) *PullRequestsRepository_MergePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewPullRequestsRepository creates a new instance of PullRequestsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestsRepository {
	mock := &PullRequestsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
