// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/eragon-mdi/pr-reviewer-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TeamsService is an autogenerated mock type for the TeamsService type
type TeamsService struct {
	mock.Mock
}

type TeamsService_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamsService) EXPECT() *TeamsService_Expecter {
	return &TeamsService_Expecter{mock: &_m.Mock}
}

// NewTeam provides a mock function with given fields: team
func (_m *TeamsService) NewTeam(team domain.Team) (domain.Team, error) {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for NewTeam")
	}

	var r0 domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Team) (domain.Team, error)); ok {
		return rf(team)
	}
	if rf, ok := ret.Get(0).(func(domain.Team) domain.Team); ok {
		r0 = rf(team)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}

	if rf, ok := ret.Get(1).(func(domain.Team) error); ok {
		r1 = rf(team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsService_NewTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTeam'
type TeamsService_NewTeam_Call struct {
	*mock.Call
}

// NewTeam is a helper method to define mock.On call
//   - team domain.Team
func (_e *TeamsService_Expecter) NewTeam(team interface{}) *TeamsService_NewTeam_Call {
	return &TeamsService_NewTeam_Call{Call: _e.mock.On("NewTeam", team)}
}

func (_c *TeamsService_NewTeam_Call) Run(run func(team domain.Team)) *TeamsService_NewTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Team))
	})
	return _c
}

func (_c *TeamsService_NewTeam_Call) Return(_a0 domain.Team, _a1 error) *TeamsService_NewTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsService_NewTeam_Call) RunAndReturn(run func(domain.Team) (domain.Team, error)) *TeamsService_NewTeam_Call {
	_c.Call.Return(run)
	return _c
}

// TeamWithMembers provides a mock function with given fields: tName
func (_m *TeamsService) TeamWithMembers(tName domain.TeamName) (domain.Team, error) {
	ret := _m.Called(tName)

	if len(ret) == 0 {
		panic("no return value specified for TeamWithMembers")
	}

	var r0 domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.TeamName) (domain.Team, error)); ok {
		return rf(tName)
	}
	if rf, ok := ret.Get(0).(func(domain.TeamName) domain.Team); ok {
		r0 = rf(tName)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}

	if rf, ok := ret.Get(1).(func(domain.TeamName) error); ok {
		r1 = rf(tName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsService_TeamWithMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamWithMembers'
type TeamsService_TeamWithMembers_Call struct {
	*mock.Call
}

// TeamWithMembers is a helper method to define mock.On call
//   - tName domain.TeamName
func (_e *TeamsService_Expecter) TeamWithMembers(tName interface{}) *TeamsService_TeamWithMembers_Call {
	return &TeamsService_TeamWithMembers_Call{Call: _e.mock.On("TeamWithMembers", tName)}
}

func (_c *TeamsService_TeamWithMembers_Call) Run(run func(tName domain.TeamName)) *TeamsService_TeamWithMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.TeamName))
	})
	return _c
}

func (_c *TeamsService_TeamWithMembers_Call) Return(_a0 domain.Team, _a1 error) *TeamsService_TeamWithMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsService_TeamWithMembers_Call) RunAndReturn(run func(domain.TeamName) (domain.Team, error)) *TeamsService_TeamWithMembers_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamsService creates a new instance of TeamsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamsService {
	mock := &TeamsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
