// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/eragon-mdi/pr-reviewer-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TeamsRepository is an autogenerated mock type for the TeamsRepository type
type TeamsRepository struct {
	mock.Mock
}

type TeamsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamsRepository) EXPECT() *TeamsRepository_Expecter {
	return &TeamsRepository_Expecter{mock: &_m.Mock}
}

// CreateTeamWithMembers provides a mock function with given fields: _a0, _a1
func (_m *TeamsRepository) CreateTeamWithMembers(_a0 domain.TeamName, _a1 domain.Members) (domain.Team, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamWithMembers")
	}

	var r0 domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.TeamName, domain.Members) (domain.Team, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(domain.TeamName, domain.Members) domain.Team); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}

	if rf, ok := ret.Get(1).(func(domain.TeamName, domain.Members) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsRepository_CreateTeamWithMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeamWithMembers'
type TeamsRepository_CreateTeamWithMembers_Call struct {
	*mock.Call
}

// CreateTeamWithMembers is a helper method to define mock.On call
//   - _a0 domain.TeamName
//   - _a1 domain.Members
func (_e *TeamsRepository_Expecter) CreateTeamWithMembers(_a0 interface{}, _a1 interface{}) *TeamsRepository_CreateTeamWithMembers_Call {
	return &TeamsRepository_CreateTeamWithMembers_Call{Call: _e.mock.On("CreateTeamWithMembers", _a0, _a1)}
}

func (_c *TeamsRepository_CreateTeamWithMembers_Call) Run(run func(_a0 domain.TeamName, _a1 domain.Members)) *TeamsRepository_CreateTeamWithMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.TeamName), args[1].(domain.Members))
	})
	return _c
}

func (_c *TeamsRepository_CreateTeamWithMembers_Call) Return(_a0 domain.Team, _a1 error) *TeamsRepository_CreateTeamWithMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsRepository_CreateTeamWithMembers_Call) RunAndReturn(run func(domain.TeamName, domain.Members) (domain.Team, error)) *TeamsRepository_CreateTeamWithMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembersByTeamName provides a mock function with given fields: _a0
func (_m *TeamsRepository) GetMembersByTeamName(_a0 domain.TeamName) (domain.Members, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetMembersByTeamName")
	}

	var r0 domain.Members
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.TeamName) (domain.Members, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain.TeamName) domain.Members); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Members)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.TeamName) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamsRepository_GetMembersByTeamName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembersByTeamName'
type TeamsRepository_GetMembersByTeamName_Call struct {
	*mock.Call
}

// GetMembersByTeamName is a helper method to define mock.On call
//   - _a0 domain.TeamName
func (_e *TeamsRepository_Expecter) GetMembersByTeamName(_a0 interface{}) *TeamsRepository_GetMembersByTeamName_Call {
	return &TeamsRepository_GetMembersByTeamName_Call{Call: _e.mock.On("GetMembersByTeamName", _a0)}
}

func (_c *TeamsRepository_GetMembersByTeamName_Call) Run(run func(_a0 domain.TeamName)) *TeamsRepository_GetMembersByTeamName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.TeamName))
	})
	return _c
}

func (_c *TeamsRepository_GetMembersByTeamName_Call) Return(_a0 domain.Members, _a1 error) *TeamsRepository_GetMembersByTeamName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamsRepository_GetMembersByTeamName_Call) RunAndReturn(run func(domain.TeamName) (domain.Members, error)) *TeamsRepository_GetMembersByTeamName_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamsRepository creates a new instance of TeamsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamsRepository {
	mock := &TeamsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
