// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/eragon-mdi/pr-reviewer-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MembersRepository is an autogenerated mock type for the MembersRepository type
type MembersRepository struct {
	mock.Mock
}

type MembersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MembersRepository) EXPECT() *MembersRepository_Expecter {
	return &MembersRepository_Expecter{mock: &_m.Mock}
}

// GetPrReviewsByMember provides a mock function with given fields: _a0
func (_m *MembersRepository) GetPrReviewsByMember(_a0 domain.MemberId) (domain.PullRequests, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPrReviewsByMember")
	}

	var r0 domain.PullRequests
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.MemberId) (domain.PullRequests, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(domain.MemberId) domain.PullRequests); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.PullRequests)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.MemberId) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembersRepository_GetPrReviewsByMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrReviewsByMember'
type MembersRepository_GetPrReviewsByMember_Call struct {
	*mock.Call
}

// GetPrReviewsByMember is a helper method to define mock.On call
//   - _a0 domain.MemberId
func (_e *MembersRepository_Expecter) GetPrReviewsByMember(_a0 interface{}) *MembersRepository_GetPrReviewsByMember_Call {
	return &MembersRepository_GetPrReviewsByMember_Call{Call: _e.mock.On("GetPrReviewsByMember", _a0)}
}

func (_c *MembersRepository_GetPrReviewsByMember_Call) Run(run func(_a0 domain.MemberId)) *MembersRepository_GetPrReviewsByMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.MemberId))
	})
	return _c
}

func (_c *MembersRepository_GetPrReviewsByMember_Call) Return(_a0 domain.PullRequests, _a1 error) *MembersRepository_GetPrReviewsByMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembersRepository_GetPrReviewsByMember_Call) RunAndReturn(run func(domain.MemberId) (domain.PullRequests, error)) *MembersRepository_GetPrReviewsByMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberStatus provides a mock function with given fields: _a0, _a1
func (_m *MembersRepository) UpdateMemberStatus(_a0 domain.MemberId, _a1 domain.MemberStatus) (domain.Member, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberStatus")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.MemberId, domain.MemberStatus) (domain.Member, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(domain.MemberId, domain.MemberStatus) domain.Member); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(domain.MemberId, domain.MemberStatus) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembersRepository_UpdateMemberStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberStatus'
type MembersRepository_UpdateMemberStatus_Call struct {
	*mock.Call
}

// UpdateMemberStatus is a helper method to define mock.On call
//   - _a0 domain.MemberId
//   - _a1 domain.MemberStatus
func (_e *MembersRepository_Expecter) UpdateMemberStatus(_a0 interface{}, _a1 interface{}) *MembersRepository_UpdateMemberStatus_Call {
	return &MembersRepository_UpdateMemberStatus_Call{Call: _e.mock.On("UpdateMemberStatus", _a0, _a1)}
}

func (_c *MembersRepository_UpdateMemberStatus_Call) Run(run func(_a0 domain.MemberId, _a1 domain.MemberStatus)) *MembersRepository_UpdateMemberStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.MemberId), args[1].(domain.MemberStatus))
	})
	return _c
}

func (_c *MembersRepository_UpdateMemberStatus_Call) Return(_a0 domain.Member, _a1 error) *MembersRepository_UpdateMemberStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembersRepository_UpdateMemberStatus_Call) RunAndReturn(run func(domain.MemberId, domain.MemberStatus) (domain.Member, error)) *MembersRepository_UpdateMemberStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMembersRepository creates a new instance of MembersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembersRepository {
	mock := &MembersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
