CREATE TABLE IF NOT EXISTS statuses (
    id SERIAL PRIMARY KEY,
    status VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO statuses (status) VALUES ('OPEN'), ('MERGED')
ON CONFLICT (status) DO NOTHING;

