// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/eragon-mdi/pr-reviewer-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MembersService is an autogenerated mock type for the MembersService type
type MembersService struct {
	mock.Mock
}

type MembersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MembersService) EXPECT() *MembersService_Expecter {
	return &MembersService_Expecter{mock: &_m.Mock}
}

// MemberReviews provides a mock function with given fields: id
func (_m *MembersService) MemberReviews(id domain.MemberId) (domain.Member, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MemberReviews")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.MemberId) (domain.Member, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(domain.MemberId) domain.Member); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(domain.MemberId) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembersService_MemberReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MemberReviews'
type MembersService_MemberReviews_Call struct {
	*mock.Call
}

// MemberReviews is a helper method to define mock.On call
//   - id domain.MemberId
func (_e *MembersService_Expecter) MemberReviews(id interface{}) *MembersService_MemberReviews_Call {
	return &MembersService_MemberReviews_Call{Call: _e.mock.On("MemberReviews", id)}
}

func (_c *MembersService_MemberReviews_Call) Run(run func(id domain.MemberId)) *MembersService_MemberReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.MemberId))
	})
	return _c
}

func (_c *MembersService_MemberReviews_Call) Return(_a0 domain.Member, _a1 error) *MembersService_MemberReviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembersService_MemberReviews_Call) RunAndReturn(run func(domain.MemberId) (domain.Member, error)) *MembersService_MemberReviews_Call {
	_c.Call.Return(run)
	return _c
}

// SetMemberIsActive provides a mock function with given fields: member
func (_m *MembersService) SetMemberIsActive(member domain.Member) (domain.Member, error) {
	ret := _m.Called(member)

	if len(ret) == 0 {
		panic("no return value specified for SetMemberIsActive")
	}

	var r0 domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Member) (domain.Member, error)); ok {
		return rf(member)
	}
	if rf, ok := ret.Get(0).(func(domain.Member) domain.Member); ok {
		r0 = rf(member)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}

	if rf, ok := ret.Get(1).(func(domain.Member) error); ok {
		r1 = rf(member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MembersService_SetMemberIsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMemberIsActive'
type MembersService_SetMemberIsActive_Call struct {
	*mock.Call
}

// SetMemberIsActive is a helper method to define mock.On call
//   - member domain.Member
func (_e *MembersService_Expecter) SetMemberIsActive(member interface{}) *MembersService_SetMemberIsActive_Call {
	return &MembersService_SetMemberIsActive_Call{Call: _e.mock.On("SetMemberIsActive", member)}
}

func (_c *MembersService_SetMemberIsActive_Call) Run(run func(member domain.Member)) *MembersService_SetMemberIsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Member))
	})
	return _c
}

func (_c *MembersService_SetMemberIsActive_Call) Return(_a0 domain.Member, _a1 error) *MembersService_SetMemberIsActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MembersService_SetMemberIsActive_Call) RunAndReturn(run func(domain.Member) (domain.Member, error)) *MembersService_SetMemberIsActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMembersService creates a new instance of MembersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembersService {
	mock := &MembersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
